import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Firago = localFont({
  src: [
    {
      path: "../public/assets/fonts/FiraGO_fonts/Roman/FiraGO-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/assets/fonts/FiraGO_fonts/Roman/FiraGO-Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/assets/fonts/FiraGO_fonts/Roman/FiraGO-Semibold.ttf",
      weight: "600",
    },
    {
      path: "../public/assets/fonts/FiraGO_fonts/Roman/FiraGO-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-FiraGO",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Firago.className} bg-[#F3F2FA]`}>{children}</body>
    </html>
  );
}
